# Generated by Django 5.2.3 on 2025-07-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('assets', 'Assets'), ('attendances', 'Attendances'), ('backups', 'Backups'), ('budget', 'Budget'), ('budgetcategory', 'BudgetCategory'), ('budgetexpenses', 'BudgetExpenses'), ('budgetrevenue', 'BudgetRevenue'), ('calendar', 'Calendar'), ('clients', 'Clients'), ('departments', 'Departments')], max_length=50)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('edit', 'Edit'), ('delete', 'Delete'), ('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('allowed', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.designation')),
            ],
            options={
                'unique_together': {('designation', 'module', 'action')},
            },
        ),
    ]
