from . import views
from django.urls import path

urlpatterns = [
    path('employees/', views.employee_list, name='employee_list'),
    path('projects/<int:project_id>/assign-task/', views.assign_task, name='assign_task'),
    path('projects/<int:project_id>/tasks/', views.project_tasks, name='project_tasks'),
    path('my-tasks/', views.my_tasks, name='my_tasks'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('select-project-for-task/', views.select_project_for_task, name='select_project_for_task'),
    path('select-project-for-view-tasks/', views.select_project_for_view_tasks, name='select_project_for_view_tasks'),
    path('tasks/<int:task_id>/edit/', views.edit_task, name='edit_task'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('accounting/budget-categories/', views.budget_category_list, name='budget_category_list'),
    path('accounting/budget-categories/add/', views.budget_category_add, name='budget_category_add'),
    path('accounting/budget-categories/<int:pk>/edit/', views.budget_category_edit, name='budget_category_edit'),
    path('accounting/budget-categories/<int:pk>/delete/', views.budget_category_delete, name='budget_category_delete'),
    path('accounting/budgets/', views.budget_list, name='budget_list'),
    path('accounting/budgets/add/', views.budget_add, name='budget_add'),
    path('accounting/budgets/<int:pk>/edit/', views.budget_edit, name='budget_edit'),
    path('accounting/budgets/<int:pk>/delete/', views.budget_delete, name='budget_delete'),
    path('accounting/budget-expense/', views.budget_expense_list, name='budget_expense_list'),
    path('accounting/budget-expense/add/', views.budget_expense_add, name='budget_expense_add'),
    path('accounting/budget-expense/<int:pk>/edit/', views.budget_expense_edit, name='budget_expense_edit'),
    path('accounting/budget-expense/<int:pk>/delete/', views.budget_expense_delete, name='budget_expense_delete'),
    path('accounting/budget-revenue/', views.budget_revenue_list, name='budget_revenue_list'),
    path('accounting/budget-revenue/add/', views.budget_revenue_add, name='budget_revenue_add'),
    path('accounting/budget-revenue/<int:pk>/edit/', views.budget_revenue_edit, name='budget_revenue_edit'),
    path('accounting/budget-revenue/<int:pk>/delete/', views.budget_revenue_delete, name='budget_revenue_delete'),
    path('assets/', views.asset_list, name='asset_list'),
    path('assets/add/', views.asset_add, name='asset_add'),
    path('assets/<int:pk>/edit/', views.asset_edit, name='asset_edit'),
    path('assets/<int:pk>/delete/', views.asset_delete, name='asset_delete'),
] 